//
//  colorAlgorithm.swift
//  FashionAppOutfit
//
//  Created by Aly Salman on 24/05/23.
//

import Foundation


//
//static let colorCombinations = [
//    ["Yellow", "Yellow", "Yellow"],
//    ["Yellow", "olive", "orange"],
//    ["Yellow", "orange", "orange"],
//    ["Yellow", "violet", "violet"],
//    ["Yellow", "blue", "red"],
//    ["Green", "yellow", "blue"],
//    ["Green", "red", "red"],
//    ["Green", "violet", "orange"],
//    ["Green", "violet", "violet"],
//    ["Blue", "blue", "blue"],
//    ["Blue", "violet", "green"],
//    ["Blue", "violet", "violet"],
//    ["Blue", "yellow", "red"],
//    ["Blue", "yellow", "yellow"],
//    ["Violet", "violet", "violet"],
//    ["Violet", "red", "pink"],
//    ["Violet", "orange", "blue"],
//    ["Red", "red", "red"],
//    ["Red", "orange", "violet"],
//    ["Red", "violet", "violet"],
//    ["Red", "green", "green"],
//    ["Red", "yellow", "blue"],
//    ["Red", "yellow", "yellow"],
//    ["Pink", "pink", "pink"],
//    ["Pink", "red", "violet"],
//    ["Pink", "light blue", "light blue"],
//    ["Pink", "green", "green"],
//    ["Pink", "yellow", "yellow"],
//    ["Black", "black", "black"],
//    ["Black", "blue", "blue"],
//    ["Black", "pink", "pink"],
//    ["Black", "red", "red"],
//    ["White", "violet", "violet"],
//    ["White", "white", "white"],
//    ["White", "green", "green"],
//    ["White", "blue", "blue"],
//    ["White", "light blue", "light blue"],
//    ["Beige", "beige", "beige"],
//    ["Beige", "orange", "orange"],
//    ["Beige", "red", "red"],
//    ["Beige", "green", "green"],
//    ["Beige", "yellow", "yellow"],
//    ["Beige", "blue", "blue"],
//    ["Beige", "pink", "pink"],
//    ["Beige", "blue", "blue"],
//    ["Beige", "violet", "violet"],
//    ["Beige", "black", "black"],
//    ["Beige", "white", "white"],
//    ["Brown", "yellow", "yellow"],
//    ["Brown", "orange", "orange"],
//    ["Brown", "brown", "brown"],
//    ["Brown", "gray", "gray"],
//    ["Brown", "yellow", "orange"],
//    ["Brown", "green", "green"],
//    ["Brown", "blue", "blue"],
//    ["Brown", "violet", "violet"],
//    ["Brown", "red", "red"],
//    ["Brown", "pink", "pink"],
//    ["Brown", "black", "black"],
//    ["Brown", "white", "white"],
//    ["Gray", "gray", "gray"],
//    ["Gray", "brown", "brown"],
//    ["Gray", "yellow", "yellow"],
//    ["Gray", "green", "green"],
//    ["Gray", "blue", "blue"],
//    ["Gray", "violet", "violet"],
//    ["Gray", "red", "red"],
//    ["Gray", "pink", "pink"],
//    ["Gray", "black", "black"],
//    ["Gray", "white", "white"],
//    ["Petroleum", "olive", "gold"],
//    ["Petroleum", "rose", "navy blue"],
//    ["Olive", "rose", "gold"],
//    ["Gold", "navy blue", "white"],
//    ["Petroleum", "navy blue", "black"]
//];
