//
//  ColorComb.swift
//  FashionAppOutfit
//
//  Created by Aly Salman on 10/09/23.
//

import Foundation



let colorCombinations = [
    ["Yellow", "Yellow", "Yellow"],
    ["Yellow", "Green", "Orange"],
    ["Yellow", "Orange", "Orange"],
    ["Yellow", "Violet", "Violet"],
    ["Yellow", "Blue", "Red"],
    ["Green", "Yellow", "Blue"],
    ["Green", "Red", "Red"],
    ["Green", "Violet", "Orange"],
    ["Green", "Violet", "Violet"],
    ["Blue", "Blue", "Blue"],
    ["Blue", "Violet", "Green"],
    ["Blue", "Violet", "Violet"],
    ["Blue", "Yellow", "Red"],
    ["Blue", "Yellow", "Yellow"],
    ["Violet", "Violet", "Violet"],
    ["Violet", "Red", "Pink"],
    ["Violet", "Orange", "Blue"],
    ["Red", "Red", "Red"],
    ["Red", "Orange", "Violet"],
    ["Red", "Violet", "Violet"],
    ["Red", "Green", "Green"],
    ["Red", "Yellow", "Blue"],
    ["Red", "Yellow", "Yellow"],
    ["Pink", "Pink", "Pink"],
    ["Pink", "Red", "Violet"],
    ["Pink", "Light Blue", "Light Blue"],
    ["Pink", "Green", "Green"],
    ["Pink", "Yellow", "Yellow"],
    ["Black", "Black", "Black"],
    ["Black", "Black", "White"],
    ["Black", "Black", "Red"],
    ["Black", "Blue", "Blue"],
    ["Black", "Pink", "Pink"],
    ["Black", "Red", "Red"],
    ["White", "Violet", "Violet"],
    ["White", "White", "White"],
    ["White", "Green", "Green"],
    ["White", "Blue", "Blue"],
    ["White", "Light Blue", "Light Blue"],
    ["Beige", "Beige", "Beige"],
    ["Beige", "Orange", "Orange"],
    ["Beige", "Red", "Red"],
    ["Beige", "Green", "Green"],
    ["Beige", "Yellow", "Yellow"],
    ["Beige", "Blue", "Blue"],
    ["Beige", "Pink", "Pink"],
    ["Beige", "Blue", "Blue"],
    ["Beige", "Violet", "Violet"],
    ["Beige", "Black", "Black"],
    ["Beige", "White", "White"],
    ["Brown", "Yellow", "Yellow"],
    ["Brown", "Orange", "Orange"],
    ["Brown", "Brown", "Brown"],
    ["Brown", "Gray", "Gray"],
    ["Brown", "Yellow", "Orange"],
    ["Brown", "Green", "Green"],
    ["Brown", "Blue", "Blue"],
    ["Brown", "Violet", "Violet"],
    ["Brown", "Red", "Red"],
    ["Brown", "Pink", "Pink"],
    ["Brown", "Black", "Black"],
    ["Brown", "White", "White"],
    //new color combinations
    ["Denim", "Denim", "Black"],
    ["Denim", "Black", "Black"],
    ["Denim", "Orange", "Orange"],
    ["Denim", "Red", "Red"],
    ["Denim", "Green", "Green"],
    ["Denim", "Yellow", "Yellow"],
    ["Denim", "Pink", "Pink"],
    ["Denim", "Violet", "Violet"],
    ["Denim", "Black", "Black"],
    ["Denim", "White", "White"],
    ["Olive Green", "Black", "Black"],
    ["Olive Green", "Olive Green", "Black"],
    ["Olive Green", "Olive Green", "White"],
    ["Olive Green", "White", "White"],
    ["Olive Green", "Olive Green", "Beige"],
    ["Olive Green", "Beige", "Beige"],
    ["Gray", "Gray", "Gray"],
    ["Gray", "Brown", "Brown"],
    ["Gray", "Yellow", "Yellow"],
    ["Gray", "Green", "Green"],
    ["Gray", "Blue", "Blue"],
    ["Gray", "Violet", "Violet"],
    ["Gray", "Red", "Red"],
    ["Gray", "Pink", "Pink"],
    ["Gray", "Black", "Black"],
    ["Gray", "White", "White"],
    ["Brown", "Yellow", "Yellow"],
];

